/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ga.tc.authentication.ui;

import com.ga.tc.authentication.bao.UserBao;
import com.ga.tc.authentication.bao.UserBaoImp;
import com.ga.tc.authentication.dto.UserInfoDto;
import com.ga.tc.common.Constants;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class AllUsers extends javax.swing.JPanel {

    private UserBao business = new UserBaoImp();
    /**
     * Creates new form AllUsers
     */
    public AllUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("All Users List"));

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        fillInUsersTable();
        jScrollPane1.setViewportView(usersTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    private void fillInUsersTable() {
        try{
            List<UserInfoDto> users = business.listAll(Constants.STATUS_LIST_ALL);
            Object [][] usersModel = new Object[users.size()][7];
            if(users != null && !users.isEmpty()){
                for(int row =0; row<users.size();row++){
                    usersModel[row][0] = users.get(row).getId();
                    usersModel[row][1] = users.get(row).getFullName();
                    usersModel[row][2] = users.get(row).getEmail();
                    usersModel[row][3] = users.get(row).getPassword();
                    usersModel[row][4] = users.get(row).getPhone();
                    usersModel[row][5] = users.get(row).getAddress();
                    usersModel[row][6] = users.get(row).getRoleId();
                }
            }
            String [] headers = new String [] {"User Id", "User Name","Email", "Password", "Phone", "Address", "Role"};
            usersTable.setModel(new javax.swing.table.DefaultTableModel(usersModel, headers));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error Ocuured :"+
                    e.getMessage(), "Error" ,JOptionPane.ERROR_MESSAGE);
        }
    }
}
